on:
  pull_request:
    branches:
      - main

jobs:
  wilco:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    name: Pr checks

    steps:
      - name: Check out project
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: "4.4"

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Wilco checks
        id: Wilco
        uses: trywilco/actions@main
        with:
          engine: ${{ secrets.WILCO_ENGINE_URL }}

      - name: Armory CD-as-a-Service Deployment
        id: deploy
        uses: armory/cli-deploy-action@main
        with:
          clientId: "${{ secrets.ARMORY_CLIENT_ID }}" 
          clientSecret:  "${{ secrets.ARMORY_CLIENT_SECRET }}" 
          path-to-file: ".github/workflows/wilco-actions.yml" 
          waitForDeployment: <true-or-false>